### ISSUE TITLE
Windows servers not supported ? :/ 

### ISSUE THREAD

**Issue by Pescad0res** [Offensive-Panda/ShadowDumper#4]
tested on 
OS Name:                   Microsoft Windows Server 2019 Datacenter

with cmd 
This version of C:\Users\xxxx\Documents\ShadowDumper.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

![image](https://github.com/user-attachments/assets/b9ed5684-8db4-4714-9ff0-7ec57d4ad6e9)

**with powershell**
./ShadowDumper.exe
Program 'ShadowDumper.exe' failed to run: The specified executable is not a valid application for this OS platform.At l
ine:1 char:1
+ ./ShadowDumper.exe
+ ~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ ./ShadowDumper.exe
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by Offensive-Panda** [comment]
> tested on 
> OS Name:                   Microsoft Windows Server 2019 Datacenter
> 
> with cmd 
> This version of C:\Users\xxxx\Documents\ShadowDumper.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
> 
> 
> ![image](https://github.com/user-attachments/assets/b9ed5684-8db4-4714-9ff0-7ec57d4ad6e9)
> 
> **with powershell**
> ./ShadowDumper.exe
> Program 'ShadowDumper.exe' failed to run: The specified executable is not a valid application for this OS platform.At l
> ine:1 char:1
> + ./ShadowDumper.exe
> + ~~~~~~~~~~~~~~~~~~.
> At line:1 char:1
> + ./ShadowDumper.exe
> + ~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
>     + FullyQualifiedErrorId : NativeCommandFailed
> 
> 



Hello, I didn't face this issue before. This issue can occur due to virus infection, files corruption or due to incompatibility. There are many solutions available for this online. You can run it in compatibility mode. But I have to check it with me. I'll prefer to recompile the code with Win32 or x64 and try again. At least the application should run on any system, but the methods of dumping lsass can vary.

**Comment by Pescad0res** [comment]
did you tried your tool on windows servers  ? because it was working fine on my test machine windows 10 then when i tried on Windows Server 2019 Datacenter i got this problem , your tool can be my way to compromise the DC during my mission :)

**Comment by Offensive-Panda** [comment]
> did you tried your tool on windows servers ? because it was working fine on my test machine windows 10 then when i tried on Windows Server 2019 Datacenter i got this problem , your tool can be my way to compromise the DC during my mission :)

I hope it will use for legitimate purposes. Yes I have checked it with me, On Windows Server 2019 Datacenter it is working fine. Please find the attached pic.
![server2019](https://github.com/user-attachments/assets/16352ce8-5c2e-4ae1-b611-fe07af37ed20)

**Comment by Pescad0res** [comment]
is it possible to share me the .exe ? maybe i messed up somthing while compling i tried to recompile but im having the same problem

**Comment by Offensive-Panda** [comment]
> is it possible to share me the .exe ? maybe i messed up somthing while compling i tried to recompile but im having the same problem

I used the same compiled binary from my github releases (V1.0)

**Comment by Pescad0res** [comment]
any ideas to troubleshoot my problem  ?

**Comment by Offensive-Panda** [comment]
> any ideas to troubleshoot my problem ?

https://www.geeksforgeeks.org/methods-to-fix-unsupported-16-bit-application-error-on-windows-10/

Read This article

**Comment by Pescad0res** [comment]
well i got probably detected by SentinelOne :')
